id: ym_i3d_msvg_dvc # the results and logs will saved in this folder ./save/id

visual_feature_type: i3d_rgb
visual_feature_folder: 'data/youmakeup/features/i3d_rgb'
invalid_video_json: []
feature_dim: 1024
train_caption_file: data/youmakeup/annotations/caption/train.json
val_caption_file: data/youmakeup/annotations/caption/val.json
gt_file_for_eval: ['data/youmakeup/annotations/caption/val.json']
eval_gt_file_for_grounding: data/youmakeup/annotations/grounding/gt_val_for_grounding.json
dict_file: data/youmakeup/annotations/vocabulary_youmakeup.json
vocab_size: 1247
save_dir: save
train_proposal_type: gt
gt_proposal_sample_num: 30
sample_method: nearest


huggingface_cache_dir: .cache
pretrained_language_model: roberta-base
gt_proposal_sample_num: 300

epoch: 25
lr: 0.0001
batch_size: 4
learning_rate_decay_start: 8
learning_rate_decay_every: 3
learning_rate_decay_rate: 0.5
weight_decay: 0.0001
text_encoder_learning_strategy: multi_step
text_encoder_lr: 0.00001
text_encoder_lr_decay_start: 8
text_encoder_lr_decay_every: 3
text_encoder_lr_decay_rate: 0.5
eval_batch_size: 16
min_epoch_when_save: 2 # save ckpt after epoch 5
train_use_amp: False
eval_use_amp: False
frame_embedding_num: 800
num_queries: 100
eval_tool_version: '2021'


# grounding settings
eval_enable_grounding: True
# Text encoder
word_context_modeling_type: attention_pool
text_encoder_learning_strategy: multi_step
enable_layer_diff_text_feature: False
# Text Context Modeling
enable_word_context_modeling: True
enable_sentence_context_modeling: True
enable_sentence_pos_embedding: True
sentence_modeling_layer_num: 1
# contrastive loss
enable_contrastive: True
enable_cross_video_cl: True
cl_schedule_time: [0, 2]
contrastive_loss_temperature: 0.1
contrastive_hidden_size: 128

dec_layers: 2
enc_layers: 2
transformer_ff_dim: 512
transformer_dropout_prob: 0.1
caption_decoder_type: standard
cap_nheads: 1
cap_dec_n_points: 4
cap_num_feature_levels: 4
soft_attention: 1
att_hid_size: 512
ec_alpha: 1.0


with_box_refine: 1
fix_xcw: 1
set_cost_caption: 0
set_cost_giou: 4
set_cost_bbox: 0
set_cost_class: 2
set_cost_cl: 2.0

caption_loss_coef: 2
giou_loss_coef: 4
bbox_loss_coef: 0
cls_loss_coef: 2
count_loss_coef: 0.5
max_eseq_length: 10
lloss_cross_entropy: 0
lloss_focal_loss: 0
lloss_gau_mask: 1